from pprint import pp
from sqlalchemy import Numeric
from sqlalchemy.sql.expression import cast, desc, func, select
import db

query = select([db.cookies])

# A ResultProxy is a wrapper around a DBAPI cursor object, and its main goal is to
# make it easier to use and manipulate the results of a statement.
result_proxy = db.connection.execute(query)
results = result_proxy.fetchall()

pp(results)

# Handling rows with a ResultProxy

first_row = results[0]
first_row[1]  # access column by index
first_row.cookie_name  # access column by name
first_row[db.cookies.c.cookie_name]  # access column by Column object

# Iterating over rows

print("\nAll the cookies:")
for row in results:
    print("\t", row.cookie_name)

result_proxy.first()  # returns the first record if there is one and closes the connection
result_proxy.fetchone()  # returns one row, and leaves the cursor open for you to make additional fetch
result_proxy.scalar()  # returns a single value if a query results in a single record with one column
print("\nResultProxy columns:", result_proxy.keys())

query = select([db.cookies.c.cookie_name, db.cookies.c.quantity])

result_proxy = db.connection.execute(query)
print("\nResultProxy columns:", result_proxy.keys())

result = result_proxy.first()
print("First row with limited columns:", result)

# Ordering

query = select([db.cookies.c.cookie_name, db.cookies.c.quantity])
query = query.order_by(desc(db.cookies.c.quantity))

result_proxy = db.connection.execute(query)
print("\nOrdering rows:")
for cookie in result_proxy:
    print(f"{cookie.quantity} - {cookie.cookie_name}")

# Limiting

result_proxy = db.connection.execute(query.limit(2))

print("\nLimiting rows to a couple:")
print([result.cookie_name for result in result_proxy])

# Functions

query = select([func.sum(db.cookies.c.quantity)])

result_proxy = db.connection.execute(query)
print("\nAvailable cookies:", result_proxy.scalar())

query = select([func.count(db.cookies.c.cookie_name)])

result_proxy = db.connection.execute(query)
record = result_proxy.first()

print("\nThe column name is autogenerated and is commonly <func_name>_<position>:")
print(record.keys())
print(record.count_1)

query = select([func.count(db.cookies.c.cookie_name).label("inventory_count")])

result_proxy = db.connection.execute(query)
record = result_proxy.first()

print("\nThe column name is labeled manually:")
print(record.keys())
print(record.inventory_count)

# Filtering

query = select([db.cookies]).where(db.cookies.c.cookie_name == "chocolate chip")
query = select([db.cookies]).where(db.cookies.c.cookie_name.like("%chocolate%"))

# like is a method of the ClauseElements instance:
# between(cleft, cright) Find where the column is between cleft and cright
# concat(column_two)     Concatenate column with column_two
# distinct()             Find only unique values for the column
# in_([list])            Find where the column is in the list
# is_(None)              Find where the column is None (commonly used for Null checks with None)
# contains(string)       Find where the column has string in it (case-sensitive)
# endswith(string)       Find where the column ends with string (case-sensitive)
# like(string)           Find where the column is like string (case-sensitive)
# startswith(string)     Find where the column begins with string (case-sensitive)
# ilike(string)          Find where the column is like string (this is not case-sensitive)

# There are also negative versions of these methods, such as notlike and notin_().
# The only exception to the not<method> naming convention is the isnot() method, which drops the underscore.

result_proxy = db.connection.execute(query)
record = result_proxy.first()
record.items()  # column, value pairs

# Operators

# add SKU- prefix
query = select([db.cookies.c.cookie_name, "SKU-" + db.cookies.c.cookie_sku])

query = select(
    [
        db.cookies.c.cookie_name,
        cast((db.cookies.c.quantity * db.cookies.c.unit_cost), Numeric(12, 2)).label(
            "inv_cost"
        ),
    ]
)

print("\nInventory value by cookie:")
for row in db.connection.execute(query):
    print(f"{row.cookie_name} - {row.inv_cost}")

# Using conjunctions

from sqlalchemy import and_, or_, not_

query = select([db.cookies]).where(
    and_(db.cookies.c.quantity > 23, db.cookies.c.unit_cost < 0.40)
)
