[tox]
envlist = py310
isolated_build = True

[testenv]
deps =
    pytest
    faker
    pytest-cov
; add a -- between the tox arguments and the pytest arguments
; tox -c tox_posargs.ini -e py310 -- -k test_version --no-cov
commands = pytest --cov=cards --cov=tests --cov-fail-under=100 {posargs}
