[tox]
; tox -c tox_multiple_pythons.ini
; add the -p flag to run the tests in parallel
envlist = py37, py38, py39, py310
isolated_build = True
skip_missing_interpreters = True

[testenv]
deps =
    pytest
    faker
commands = pytest
