[tox]
; tox -c tox_coverage.ini -e py310
; use the -e flag to run tests in a specific environment
envlist = py310
isolated_build = True

[testenv]
deps =
    pytest
    faker
    pytest-cov
commands = pytest --cov=cards
